### ISSUE TITLE
Hotel Roommate Assignments

### ISSUE THREAD

**Issue by txtbks** [sparcopen/opencon#114]
The topic of how we assign hotel roommates came up on the September 29 OC call, so opening this up so we can discuss. The main question is around whether we want to randomly match people or assign based on region in years past—or something else. Welcome @sparcopen/oc-opencon's thoughts!

**Comment by thomasmboa** [comment]
My talk was to share with you some comments from our last meeting in
Washington.

Because it seems like room was matched depending of the colour of skins,
meaning that black african have shared room with black african.

I am sure that it was not your intention, but sharing room due to region
can be problematic. It is better to do it randomly, this will be bring more
diversty in interactions during/after, inside/outside the meeting.

2017-09-29 12:43 GMT-04:00 Nicole Allen <notifications@github.com>:

**Comment by guichactis** [comment]
The issue raised my attention as well, and I remember asking Nicole about hotel roommate assignment and she confirmed that it was made on a regional basis. I understood that this wasn't due to any bad intentions and it didn't exactly represent a problem for me, but I agree with Thomas that maybe a random approach could bring more diversity and, at least for me, may feel more inclusive. I think it could be considered for next year's registration process.

**Comment by txtbks** [comment]
Circling back to this thread because we're about to make roommate assignments. Based on our discussion on the call and the feedback here, we will make assignments with an eye to matching people from different regions. If anyone else on @sparcopen/oc-opencon has feedback please let me know today!
