### ISSUE TITLE
September Community Call on Open Government 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#14]
Need to plan agenda and schedule speakers.

**Comment by nshockey** [comment]
Love this theme. I would be keen to get a discussion going between early career professionals in government while the application process is still open, so we can hopefully get more of those types to apply. I believe @guichactis was interested in possibly convening a discussion for early career government officials. Would this be realistic to organize by mid-July?

**Comment by JosephMcArthur** [comment]
Given I think we already have a fair few speaker ideas, I think it's possible at least.

**Comment by guichactis** [comment]
Would be glad to help with this. My office schedule might be a problem since I usually cannot be available for the regular time the community calls are convened, so it would be great for me if we could delay it a few hours . I think I can reach out to Eunice (who works in Mexico's National Research Council as Deputy Director for the national system of scientific open access repositories) and Robertus (from Indonesia's presidential team of open government data). Since I'm exclusively working with opening **research** data I could also try to connect  with the people working on open government data here in Argentina to see if they could be in the call.

**Comment by char-siuu-bao** [comment]
Wanted to check in on whether September would still be used to chat about Open government! We were hoping to talk about building diverse/equitable communities when doing Open work on the community call today, but we ended up having such a fruitful discussion about satellites that we didn't get to it! Lots of folks were interested in having that conversation, so I'm hoping to reschedule it for a future call (and invite some guest speakers) — August is an OA week theme, so wanted to check if September would still be slotted for a conversation around government! 
@JosephMcArthur @nshockey

**Comment by JosephMcArthur** [comment]
@guichactis would you be able to make the [September call](http://www.opencon2017.org/september_2017_community_call) and be willing to help facilitate? I know you said your schedule can be tricky,  but I'm wondering if that was just in relation to a July call.

**Comment by guichactis** [comment]
@JosephMcArthur I would definitely like to help facilitate this call! My office hours are quite tricky indeed (I'm here from 8am to 6/7pm GMT -3 so I need to know what the time of the call would be in order to see if I can arrange my schedule and leave early that day (sometimes there are reunion's rooms available, especially on Fridays, but otherwise I cannot stay here because I won't be able to speak from my desk). 
Also, I would appreciate if I could speak with @lorrainechu3n and you first to see what the call's dynamic should be and what you expect from it. I've participated of a few community calls but it would be nice to have it clear from the facilitator's point of view :)

**Comment by char-siuu-bao** [comment]
@guichactis - the call is currently scheduled for September 27 at our usual call time http://www.opencon2017.org/september_2017_community_call 

12pm ET — so 1PM in Argentina, I believe! 

Definitely happy to chat about what it's like to facilitate community calls. I can put together a facilitation guide (I think @JosephMcArthur has been meaning for us to do this for a while anyway!) and send it to you this week, and if you want, we can also schedule a google hangout beforehand to answer any Q's you may have!!

**Comment by char-siuu-bao** [comment]
@JosephMcArthur and @nshockey do you have ideas for who to reach out to as speakers?

**Comment by guichactis** [comment]
If I'm allowed to suggest, last year I met at the conference two very
interesting alumni working as government officials on open related issues:
- Eunice Mercado from Mexico's National Research Council, who works
implementing the national open access green route's policy.
- Robertus Theodore from the Indonesian's Executive Office of the
President, who works at the Open Data policy.
I'll check tomorrow the office's schedule for the 27th to see if I can
leave at the time of the call and get back to you ASAP.


On 7 Aug 2017 6:40 p.m., "Lorraine C." <notifications@github.com> wrote:

@JosephMcArthur <https://github.com/josephmcarthur> and @nshockey
<https://github.com/nshockey> do you have ideas for who to reach out to as
speakers?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sparcopen/opencon/issues/14#issuecomment-320788465>,
or mute
the thread

**Comment by char-siuu-bao** [comment]
Hey @guichactis!! Thanks so much for your suggestions!! Best to check with Joe and Nick to see what they think, but they both seem like they'd be great speakers for the call.  I'll follow up with them!

I've put together a little document to guide community call facilitators - let me know if this is helpful for you to prepare! :) https://docs.google.com/document/d/1CN_eq-Z1sBJaNfNn6s03ReY-7JVbFYqj595Hmg8SjaY/edit?usp=sharing

**Comment by JosephMcArthur** [comment]
@lorrainechu3n just sent you a bunch of info from last year on speakers suggested by @nshockey and @txtbks. Also, I've added a lot of content/edits to the facilitation guide, thanks for kicking it off so well!

@nshockey any thoughts on the speakers suggested above:
>- Eunice Mercado from Mexico's National Research Council, who works
implementing the national open access green route's policy.
>- Robertus Theodore from the Indonesian's Executive Office of the
President, who works at the Open Data policy.

@guichactis, any word on if you'll be able to join?

**Comment by guichactis** [comment]
My boss has been out of the office the whole past week. He'll be back tomorrow so I'm hoping to mention this just to check with him if it's okey for me to use one of the meeting rooms and be absent from my desk for as long as the call lasts. Thanks both for your work on the facilitation guide!

**Comment by guichactis** [comment]
I spoke with my boss yesterday and he's perfectly fine with me facilitating
the call during office hours :) Just let me know @lorrainechu3n
<https://github.com/lorrainechu3n> if we can arrange a google hangouts vc
for me to prepare for it.

On 14 Aug 2017 4:43 p.m., "Joseph McArthur" <notifications@github.com>
wrote:

@lorrainechu3n <https://github.com/lorrainechu3n> just sent you a bunch of
info from last year on speakers suggested by @nshockey
<https://github.com/nshockey> and @txtbks <https://github.com/txtbks>.
Also, I've added a lot of content/edits to the facilitation guide, thanks
for kicking it off so well!

@nshockey <https://github.com/nshockey> any thoughts on the speakers
suggested above:


   - Eunice Mercado from Mexico's National Research Council, who works
   implementing the national open access green route's policy.
   - Robertus Theodore from the Indonesian's Executive Office of the
   President, who works at the Open Data policy.

@guichactis <https://github.com/guichactis>, any word on if you'll be able
to join?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sparcopen/opencon/issues/14#issuecomment-322288917>,
or mute
the thread

**Comment by char-siuu-bao** [comment]
@guichactis, my apologies for the late reply! Great to hear that you'll be able to facilitate.  Let's set up a time a week or two before the call to get you prepared!  Could you give me a few times that you're available the week of September 11 and September 18 to chat?  My schedule is more flexible on Thursdays/Fridays if that helps! 

I'll start reaching out to speakers this week.  Eunice and Robertus both sound like they'd be great speakers! I'll send them an email shortly. Thanks for those suggestions!

**Comment by char-siuu-bao** [comment]
Potential speakers contacted so far: 

- Eunice from Mexico (working on Mexico national OA policy)
- Robertus from Indonesia (working on Open Data policy - but it may be too late in his time zone to participate - 11 pm!)
- Laura from Liberia (who has plans to meet with the Ministry of Education to talk about Open)

**Comment by guichactis** [comment]
Sorry for the delay! Yes! Fridays are better for me too, and the best time is after 2 pm Argentina. Let me know what you think to block the date and time.

**Comment by char-siuu-bao** [comment]
We've had Carly (USA) and Eunice (Mexico) agree to be on the call! Hopefully can secure one more speaker before the end of the month as well — if anyone has more suggestions on who to contact, that would be greatly appreciated!

@guichactis — how about Friday September 15th, 2:30pm Argentina time? Would that work for you? (@josephmcarthur, if you're able to join then as well, that would be great!)

**Comment by guichactis** [comment]
great, I'll save the date @lorrainechu3n

2017-08-29 13:05 GMT-03:00 Lorraine Chuen <notifications@github.com>:

**Comment by JosephMcArthur** [comment]
We did this call & it was wonderful :)
