### ISSUE TITLE
OpenCon's Program Themes

### ISSUE THREAD

**Issue by JosephMcArthur** [sparcopen/opencon#22]
Tagging @nshockey to expand this, but this is here as a reminder & place to start putting notes.

**Comment by nshockey** [comment]
To get a sense of themes we've highlighted during past OpenCons, I've listed the panels for each year below along with a link to the full program:

2016 panels ([full program](http://www.opencon2017.org/opencon_2016_archive)): Culture change, research evaluation, equity and open, successful participant projects
2015 panels ([full program](http://www.opencon2017.org/opencon_2015_archive)): Epic open wins, successful participant projects, research evaluation, OER: policy & practice
2014 panels ([full program](http://www.opencon2017.org/opencon_2014_archive)): current state of open, innovative publishing models, impact of open, successful participant projects

We've tried to focus on themes that are action oriented and created discussion that we hoped could translate into action once participants returned home. This led to moving programming that was oriented toward bringing participants up to speed on issues (e.g. state of open, epic open wins) to pre-conference webcasts in order to provide more time for topics participants might organize around (e.g. culture change, research evaluation).

To begin with, it would be helpful for the Organizing Committee to brainstorm ideas for topics that you feel are especially pressing / relevant right now and that lend themselves to taking action following the conference. It would also be helpful to hear which types of themes / sessions you felt were most valuable to you personally.

It's also important to keep in mind that ~75% of participants will be attending their first OpenCon, so repeating broad themes isn't necessarily repetitive for most of those in the room.

One we define broad themes, we'll translate those into specific blocks of programming (i.e. panels, workshops, keynotes).

**Comment by chartgerink** [comment]
Don't know if it's inappropriate to jump in here without invitation, but maybe "Keeping open open"?

Polarization being such a topic nowadays, and discussion in the OA/OD/OS community sometimes reverting into just obscenity or creating boxes in front of us while breaking down those behind of us, I think it would be worthwhile theme to self-reflect. It doesn't preclude that we can still celebrate the victories of the year past, of course, but we shouldn't become complacent of ourselves as well. Moreover, in 50 years time the things we are advocating for might have become outdated and change needs to occur again. Self-reflection now to prevent things from becoming so engrained and hard to change is wortwhile, in my opinion. 

We don't want to become disgruntled old people discouraging the younger people as we age? I know I don't 🥂

**Comment by nshockey** [comment]
Thanks, @chartgerink! Do you have an idea of how the theme of "keeping open open" might translate into programming?

**Comment by JosephMcArthur** [comment]
Tagging @sparcopen/oc-opencon to make sure all the OC see this message!

**Comment by npscience** [comment]
I think @chartgerink has a good point, which could be linked into a theme emerging in my own work: how we put thoughts into actions as a whole community. Different opinions here re how open to be (mix of radical openness vs fear of 'bad actors'), but I'm sensing a general wish to share for efficiency purposes and to produce the best work we can (multiple contributors >> lone actors). A panel on learning lessons from other open, flexible and dynamic communities could be interesting as well as to offer actions to new and old participants with respect to solidifying the network.

Examples:
- collaborative authoring projects (as Jon T does)
- successes and failures of open source communities like Wordpress, wikipedia, etc
- how to build a local community from scratch (plenty of egs from within opencon community)
- considering effective global communities - understanding cultural differences, welcoming people, being aware of our own situational biases
- a note on codes of conduct, different applications of them in labs and online communities

Just a few ideas for thoughts.

**Comment by InquisitiveVi** [comment]
Nice thoughts @chartgerink and @npscience 
I have some suggestions (incoherent at the moment). Maybe they don't fit into the big picture/ major theme but we can think of prioritising them on workshops or unconference sessions: 
- Citizen science projects
- Open practices in patient support groups 
- Preregistration: a framework for research rigour and how to be flexible with unexpected findings
- Organising early career researchers rampage group (if Corina Logan could join)

**Comment by InquisitiveVi** [comment]
@chartgerink Do you think, some discussion on legal issues or copyright barriers to unlock open will be useful to the community? I am thinking loud about this as an additional exercise for advocacy day. Will it be helpful to create learning values from the case against Diego Gomez and maybe Elsevier's $15 Million penalty on Sci-Hub. I can already imagine this might end up creating binaries on legal morality.  Julia Reda (Member of European Parliament) might be helpful here (Kind attention: Shawn Daugherty).

**Comment by chartgerink** [comment]
Good question @nshockey. Off the top of my head I'd suggest the following:

1. The open community closing up? Preventing groupthink
	* In essence, polarization is just groupthink that closes the discussion.
2. Achieving unity across Data, Access, Science
	* I frequently see Open Data trumping Open Access arguments (or any other combination) which totally foregoes that all of the changes that are suggested strive for a more sustainable science.
3. Diplomacy versus revolution: what does open science really need?

@npscience I agree promoting diversity is key and sometimes we have to choose to have less diversity (just like when you have a vision it is necessary to not let the naysayers make you give up)

@inquisitivevi I think legal discussion will not be very stimulating at the conference itself (legal talk is boring IMO, sorry), and would prefer stimulating thought about how to use the incentive systems currently in place to promote change. For example, how can we operationalize metrics in such a way that they actually promote good science as universities fight for better rankings? I have some ideas about this, but won't claim the discussion by sharing here :smile:

**Comment by InquisitiveVi** [comment]
@chartgerink I will be glad to discuss those ideas on metrics to promote good science. I will send you an email soon. 
 I partly agree with your comment on limiting diversity of naysayers (in response to NP's comment). However, including them in the open dialogue will help us crack what other irrational fears are holding them back. Personally I would prefer devil's advocate than naysayers, in this case.

**Comment by rchampieux** [comment]
Great ideas  @chartgerink @npscience and @InquisitiveVi.  I'm particularly keen on the themes of putting our thoughts into action and EDI.  The latter can be approached in two important directions, I think:  the importance of prioritizing and building for EDI within the context of the open community (to ensure we're not just working on behalf of dominant needs/goals), but also how openness can be used to address social justice issues.

Some other theme ideas:

* Building and leveraging partnerships for openness

I think this is a key ingredient for getting initiatives of the ground and affecting change, but it can seem daunting

* The research of openness

I'm a nerd for this stuff, but I think a panel of presentations on the current state and outcomes open access, open data, and OERS can drive would be inspiring

* Open workflows

@InquisitiveVi mentioned pre registration and patient support groups, maybe we could expand this idea a bit to address examples of open workflows and practices across different domains.

**Comment by npscience** [comment]
> Building and leveraging partnerships for openness
> I think this is a key ingredient for getting initiatives of the ground and affecting change, but it can seem daunting

@rchampieux  This sounds like a great idea to me, particularly since some of those partnerships may be forged at OpenCon itself, so giving people the means and courage to do so could be very effective. (I'm not sure what EDI means?)

> Preregistration: a framework for research rigour and how to be flexible with unexpected findings
> Organising early career researchers rampage group (if Corina Logan could join)

@InquisitiveVi these sound ripe for exploration, to me at least. I agree with @rchampieux's suggestion of a more broad theme that covers open workflows.

@chartgerink @InquisitiveVi I wasn't suggesting to include naysayers (in fact, I'm very much not, I think we should be as optimistic and positive as possible especially at OC). Instead, I think there's opportunity to learn from different perspectives and sources that we may not have yet engaged. A couple of examples:

* The more technical/developer types we can get involved, the better, as they offer the skillsets to develop technical solutions (and to teach computational skills to others). I don't think this is particularly new - OpenCon helps to marry the ambitious ideas of some people with the technical knowhow of others - but I'd welcome a theme that encourages more of this cross-domain interaction.
* Getting some insight from behavioural psychology/sociology could help with coming up with more effective or new ideas for advocacy and adoption.

I think these examples could be useful for both your groupthink and your diplomacy [advocacy] vs revolution [potentially technological, but not exclusively] ideas, @chartgerink.

**Comment by rchampieux** [comment]
> I'm not sure what EDI means?

@npscience EDI is Equity, Diversity, and Inclusion (sorry, I should have typed that out in the first place).  Also - thanks for including some markdown goodness in your comment ">" is new to me!  🏆

**Comment by ivonnnelujano** [comment]
I think @npscience 's suggestions are vey comprehensive of the current concerns in the [diverse] open landscape. I remember last OC I heard many comments on the relevance of being aware of our differences in 'openness' understanding and the richnessess of that. But, as some of you commented, this diversity sometimes is a tough thing when we try to take actions as a community, not just for certain interests or models. That's why I agree with @rchampieux and support the idea of including EDI as a theme towards social justice reflection/action. In that sense, I also agree with @chartgerink in including some self-reflection panel, where we can discuss on polarization & preventing groupthink. I consider this could be a great 'hors-d'œuvre' for those who will be attending OC for the first time. 

In addition, I would like to say that while Diego Gomez still faces the possibility of prison after the appellation (so cases like this one could still occurring), I think the theme of copyright barriers should be on the table as @InquisitiveVi pointed out. 

Since I'm re taking some dance projects, I wonder: do you think openness is an artists' concern? In one hand, we know people from that fields are also pushing a more open model to share contents. In the other hand, I really think it is necessary to emphasize the complementary of science(s) and arts. Anyway, this possible could be more a topic for an unconference session. Suggestions are welcome :)

**Comment by rchampieux** [comment]
As both @ivonnnelujano and @InquisitiveVi point out, I agree that copyright and licensing are important issues, and we can find a way to explore this topic in a compelling way (and avoid the dry/boring approach @chartgerink critiqued).  Exploring this topic could also offer a really interesting opportunity to explore the intersection of openness and the creative arts (as @ivonnnelujano suggested).  

Additionally, there are some really interesting discussions/questions happening around data and copyright/licensing that we could incorporate into a panel.

**Comment by chartgerink** [comment]
I agree that copyright is important, and considering the discussion maybe we should do something to make it a bit more fun while communicating the info. I tried to engage researchers about copyright with a [microsite](https://libscie.github.io/libcopy). My primary concern is that we again fall back into `CC WTF` discussions :evergreen_tree: 

If we want to talk behavioral psychology, preregistration, etc, I think we should definitely consider reaching out to the [Center for Open Science](https://cos.io) who do behavioral stuff (e.g., preregistration challenge, TOP guidelines of transparency for journals) to change the research system. They also create a lot of tech, and I must say I missed them at previous OpenCon's. 

For EDI, @rchampieux, maybe it is good to revisit some of the roots of openness and have those who we so often say to advocate for come along. Why not have a Small- Medium sized Enterprise (SME) come along and tell us what they can do if they had access or how they gain access now. Try and reach out to some interested citizens who do science as a hobby and have them tell their story. We could invite multiple, and have a parallel session where we all meet them and talk about their motivations, what they need. This could create a lot of energy and maybe even some new insights. The "Human library" idea (see also http://humanlibrary.org/meet-our-human-books/). Main thing here would be finding those people of course, but Berlin has a science week just before OpenCon so might able to lift some people over into the OpenCon schedule.

**Comment by npscience** [comment]
+1 to COS sugggestion

This discussion of EDI (thanks @rchampieux :)) and copyright makes me think about these questions: what are we asking of people when we ask them to be open? What are the costs to the individual? How do these costs differ depending on your own circumstance? There's a big difference between asking the Chris of today to share something and asking the younger Diego or Chris to - bridging the copyright literacy gap is difficult and time-consuming, not knowing about copyright can have a huge cost. Do we appreciate the risks we open people up to (obviously unintentionally) when we share our values? Also, what's the realistic impact on someone's career now if they buck the trend and go open? I feel we don't understand this yet, the evidence base is very young still IMO.

Maybe some reflection about appreciating the barriers and costs to every individual could be useful and could tie together the EDI and copyright angles?

I also wonder if The Human Library (which looks awesome, thanks for the link) can offer some perspective here, since they have a lot of brave people willing to make themselves vulnerable for the cause of greater understanding.

It sounds like there are some specific potential speakers/topics coming out here already. I love the dance / art&science suggestion @ivonnnelujano!

**Comment by pennybphd** [comment]
+1 to that Naomi, the risks/barriers of open were something I was keen to address last year (and talked about in my application) but only ended up speaking about briefly. Strategies for overcoming barriers (and recognising privilege), setting up mentoring networks etc would be really positive. 

I'm also very pro building links between arts (including practice-based arts research - look at the [Defiant Objects](https://defiantobjects.wordpress.com/) project - and the physical and social sciences and humanities. There's also some interesting stuff around Open approaches to smart cities (Alison Powell at LSE is awesome) and connecting Open to publics beyond OA and open research data.

I wonder if building bridges, not walls (stealing from the anti-Trump and anti-racism movements here) might be a useful theme?

I'm currently research assistanting on a project that follows up [TANDEM](http://www.tandem-wacren.eu/), which is building links between African and European research networks and building capacity in Central African universities and academic libraries - including around repositories, resource shortages, OER, OA and Open Data. My [boss](http://www.tandem-wacren.eu/) on that project is from the Caribbean and has worked with many developing countries, but is based in Sheffield, and building links between the Global North and South that aren't just white knighting or cheerleading is really important.

**Comment by Bubblbu** [comment]
+1 for a "fresh" copyright discussion

---

+1 science/arts. I would also be interested in addressing/including philosophy (of science) which might not sound like the most actionable topic, but I do believe that critical (self)reflection and deliberation could benefit from e.g. philosophy of technology. But I am aware that this might be a better fit for an unconference session :D

---

> Do we appreciate the risks we open people up to (obviously unintentionally) when we share our values? Also, what's the realistic impact on someone's career now if they buck the trend and go open?

In the light of Diego Gomez' case it might be important to consider the potential impact of open practices on students. What kind of impact could an *open* lecturer/tutor/supervisor (and their values) have on the future of a student.

----

A small (at least for now) scandal is unfolding in Austria because a study financed by the ministry for integration had been edited/revised considerably by clerks of the ministry (and eventually the author). The (heavily changed) pilot study was then used in the campaign for upcoming snap elections. Even though the case is being publicly discussed in the context of fraud and academic misconduct, little attention has been paid to issues around transparency and open practices in general.

Maybe this story and similar cases could be great discussion starters for the potential positive impact of *Open* outside of the academic context.

**Comment by guichactis** [comment]
+1 to @ivonnnelujano & @InquisitiveVi science/arts & citizen science projects ideas - I think bringing in people from these areas or proposing a discussion around them would be a catalyzer for introducing @chartgerink "keeping open open" by confronting more traditional approaches to science with that of those who access or intervene in the research processes from the "outside" of the scientific community. 
+1 to @ivonnnelujano on continuing the conversation around Diego's case and @Bubblbu suggestion of introducing Open Practices as a theme. Maybe something like "Good Open Practices" to create awareness, where copyright and other regulations could be discussed. 

>    The research of openness
I'm a nerd for this stuff, but I think a panel of presentations on the current state and outcomes open access, open data, and OERS can drive would be inspiring

I'm so into this idea @rchampieux ! I think it's extremely important to provide participants with updated information and on-going research projects, since it could be information to be used as evidence when advocating for open related policies  .

**Comment by rchampieux** [comment]
>  @pennybphd ....links between the Global North and South that aren't just white knighting or cheerleading is really important.
>  @Bubblbu In the light of Diego Gomez' case it might be important to consider the potential impact of open practices on students. What kind of impact could an open lecturer/tutor/supervisor (and their values) have on the future of a student.
> @npscience Maybe some reflection about appreciating the barriers and costs to every individual could be useful and could tie together the EDI and copyright angles?

💯  on these EDI threads.  It could be interesting to think about how we could explore these questions and issues through local case studies.

@Bubblbu your comments also make me think of the theme of mentoring more generally and its relationship to the efficacy and evolution of our community members' roles as open research advocates and practitioners.

**Comment by Bubblbu** [comment]
Just saw this tweet by the OA Button: [https://twitter.com/OA_Button/status/887037727643979776](https://twitter.com/OA_Button/status/887037727643979776)

![image](https://user-images.githubusercontent.com/6946077/28288027-1441c732-6b3e-11e7-8cad-7c54e3b6f6d7.png)


Discoverability and findability might also be interesting topics. How to deal with information with an increasing availability (and accessibility) of publications. At Open Knowledge Maps we are also trying to increasingly focus on these aspects, as they are often merely addressed as side topics/effects

**Comment by npscience** [comment]
Talk at ASAPbio meeting today (around preprints ecosystem) included need to develop educational resources to inform researchers on licensing, so they can make better decisions when it comes to signing away copyright, etc. Stimulating project on this at opencon could be really useful, if can then collaborate with ASAPbio on this. cc @chartgerink @Bubblbu @rchampieux @InquisitiveVi @ivonnnelujano

**Comment by chartgerink** [comment]
Yes! I tried getting started on this [here](https://libscie.github.io/libcopy). Many researchers don't want legalese nor do they actually want to think about it. I've been thinking about how to get them to engage, because mostly I get refusals of discussing the topic or waiving of the problem. 

The [APA takedown requests](http://retractionwatch.com/2017/06/16/following-outcry-american-psychological-association-refocuses-takedown-notice-program/) recently was one of the few things that made a few people more aware, but minimally so. 

I agree it's a good topic, but wonder how much effective work we can do during OpenCon on this? Because we all understand the importance and might get some massive groupthink on it being important  and how to get people to engage (because the most reluctant people won't be at OpenCon). It could be a good starting point @npscience

**Comment by char-siuu-bao** [comment]
Apologies for being so late on this thread! I think the above ideas are great, but as @rchampieux and some others have suggested, it would be great to have EDI-related theme—perhaps not explicitly "Equity and Open" like last year, but a more specific topic.  I'd like to see specific discussions on advancing Open across geographical contexts (and the specific challenges that come with different contexts). Maybe a discussion on decolonizing (Open) scholarship?  Also, Leslie Chan has some great slides/talks on how OA has in some ways perpetuated inequities and power dynamics in global knowledge sharing rather than disrupted them: https://www.slideshare.net/lesliechan

I'd also be curious to see a panel discussion that touches on situations in which Open might not apply or might be detrimental (e.g. for certain cultural communities).

**Comment by JosephMcArthur** [comment]
Thanks to everyone for their input here. 

Our approach here is discussed & approved by the OC, with minutes kept. In short, we're going to try to continue to try and center:
* Diversity, Equality & Inclusion
* Culture change
* ECR's as key voices
 in the programming, while providing a lot of time for participants to chose their own programming through unconferences & doathons. Some big shifts are discussed in #78 & #80 & #4 . 

We like the ideas above and would encourage anyone who feels like their ideas don't fit into the above focus areas to raise these through the unconference/doathon.
