### ISSUE TITLE
OpenCon 2017 Website updates 

### ISSUE THREAD

**Issue by char-siuu-bao** [sparcopen/opencon#23]
- [x] Homepage text
- [x] Sliders
- [ ] Informational pages
- [x] Request referral pages
- [x] Sharing resources page
- [x] Application submission page ([/opportunities](http://www.opencon2017.org/opportunities))
- please add more as you think of them!

**Comment by char-siuu-bao** [comment]
@txtbks do we need a new google form for referral requests this year? http://www.opencon2017.org/request_referal_code

**Comment by txtbks** [comment]
It might be helpful to lay out our process for assigning/distributing referral links first. From a technical perspective, there is no formal need for registration, but we do need some system for tracking amongst ourselves who has what referral code. @JosephMcArthur?

**Comment by char-siuu-bao** [comment]
@nshockey Joe is going to update the homepage to include broad information about the 3 issue areas before Tuesday. Could you OK the google doc text? https://docs.google.com/document/d/1wpXsmevfxxeK82HQ5FiZEjpm2rOYAQAGosalVO-0Xww/edit#heading=h.xztqaywy0gtq (I think we're going to go with the 2nd tagline)

**Comment by nshockey** [comment]
Content is good to post. I'm still trying to think of a more engaging / active tagline, but seeing it on the homepage might help with this.

**Comment by nshockey** [comment]
Added application submission page at /opportunities to the list of pages above to be updated by COB Monday.

**Comment by JosephMcArthur** [comment]
I've updated the homepage on preview with our new intro to open text. I have two version, the one that can currently be seen that's a **bit** nicer to look at - and the very basic changes we've previously discussed. 

If people, especially @lorrainechu3n, look [here](https://righttoresearch.nationbuilder.com/admin/sites/1/pages/26/preview?browser_id=default&logged_in=0&theme_id=55814e112213932968000001) and think what I have is better than a simple clone of the 1st black box then that would be good to know.

**Comment by char-siuu-bao** [comment]
Hey @JosephMcArthur! I really like the way it's formatted! I wonder if it should almost come before the first black box? (though I would understand arguments against that) 

One separate, small nit picky thing... for the new mini slider showcasing our sponsors, would it be possible to increase the padding/white space between the slider and the "Organized by R2RC/SPARC" section underneath? It looks really cramped right now and it's not immediately clear they are two sections until you realize one is a slider.

**Comment by JosephMcArthur** [comment]
I'm not totally averse to this idea. If we flipped it, we'd need to have very clear button's to get to the next panel fast & get folks applying (so, under the "We’re working to make online research & educational materials free to read, share, and modify for all." we'd need a button saying something like "get involved" or "learn more about OpenCon". I've mocked up what I think that would have to look like now on the preview link above. 

I think at this point if we do this is an @nshockey decision. 

Will get the padding fixed, it annoys me too.

**Comment by char-siuu-bao** [comment]
Could I get a second pair of eyes on the updated sharing resources page @JosephMcArthur?? Thank you! http://www.opencon2017.org/sharing_resources

**Comment by guichactis** [comment]
@lorrainechu3n here a few corrections to the Spanish version:

Queremos compartir esta convocatoria que puede ser de interés para estudiantes. Desde el 1 de agosto, es posible hacer solicitudes para asistir OpenCon 2017 el 11 a 13 de noviembre en Berlina/ **del 11 al 13 de noviembre en Berlin**. Se recomienda a los interesados hacer su solicitud/ **realizar su aplicación** con tiempo. Los interesados pueden solicitar una beca de viaje, total o parcial, que se otorgará a la mayoría de los aceptados. OpenCon 2017 convocará a estudiantes y profesionales académicos en estadíos tempranos de **sus** carreras de todo el mundo. OpenCon sirve como un poderoso catalizador de proyectos lidereados por la próxima generación para avanzar en tres areas/ **áreas** de enfoque - Acceso Abierto, Educación Abierta, y Datos Abiertos. Mediante un programa de conferencias magistrales, mesas redondas, talleres y hackathons, los participantes podrán desarrollar habilidades en áreas clave de sensibilización institucional para la coordinación de campañas a nivel nacional de forma eficaz. Solicite temprano/

**Comment by char-siuu-bao** [comment]
@guichactis Thank you so much for editing the translation! That was my attempt at updating the translation which is why there are grammatical errors. Thank you again!

**Comment by guichactis** [comment]
I can try to translate the other posts as soon as this afternoon (I leave office at 4 so it can be ready by 6pm) - if you have the posts somewhere else and can make a google doc with two columns (one with the english version and the other for me to translate each paragraph) would be awesome (and then once I've finished you can just work with the document. I can translate and (if she's available) @ivonnnelujano could check for any mistakes (or to suggest more neutral translations since sometimes some things differ in how they're said in different Spanish speaking countries). Let me know!

**Comment by char-siuu-bao** [comment]
@guichactis @ivonnnelujano That would be so helpful! Even if we don't get it up today, it would be useful later on in the application period.  I've created a google doc here: https://docs.google.com/document/d/1LvcfUi7C-bRQWlm9WT-T_EKFE7IwlsgSeO9tfIlA_oU/edit?usp=sharing Thanks again!

**Comment by guichactis** [comment]
@lorrainechu3n done. There is a specific comment for Ivonne to check. If you want me to translate the other posts and tweets let me know

**Comment by JosephMcArthur** [comment]
- [x] faq
- [ ] twitter pic on /thank_you

**Comment by char-siuu-bao** [comment]
@guichactis @ivonnnelujano thank you so much with your help on the translations!! I'm so sorry about the inconvenience, but we've actually made some updates to the sharing text: 

Applications to attend OpenCon 2017 on November 11-13 in Berlin, Germany are now open! Most of those who are invited to attend will receive full or partial travel funding, if needed.

OpenCon brings together early career researchers, librarians, and students from around the world to connect and empower the next generation of leaders to open up research and education in their communities. Past conferences have featured presentations from established figures such as Jimmy Wales (cofounder of Wikipedia) and Julia Reda (member of the European Parliament) alongside those from early career leaders.

Apply to attend OpenCon at http://www.opencon2017.org/apply 

Applications will remain open until August 1st. The benefits of applying for OpenCon 2017 extend far beyond attending the Berlin event—those who apply will have the opportunity to get connected with new collaborators, learn about scholarships to attend related conferences, and actively participate in a larger community. Attendance at OpenCon is by application only, and students and early career academic professionals of all experience levels are encouraged to apply.

If it's too much work to update, don't worry about it, the old blurb is still useful!

Lorraine

**Comment by guichactis** [comment]
@lorrainechu3n ,

This will be the updated translation: (@ivonnelujano I took the suggestion
of replaicing usted for a more formal pronoun - I'll use vos instead of
tu's conjugation for spreading it with my Argentinian contacts)

¡Se encuentra abierto el proceso de postulaciones para asistir a OpenCon
2017 del 11 al 13 de noviembre en Berlín, Alemania! La mayoría de quienes
son invitados a asistir recibirán financiamiento total o parcial para el
viaje, en caso de necesitarlo.

OpenCon reúne profesionales académicos en estadios tempranos de sus
carreras, bibliotecarios y estudiantes de todo el mundo para conectar y
empoderar a la próxima generación de líderes para la apertura de la
investigación y la educación en sus comunidades. Las conferencias
anteriores contaron con presentaciones de figuras tales como Jimmy Wales
(co-fundador de Wikipedia) y Julia Reda (miembro del Parlamento Europeo)
junto con las de líderes en los inicios de sus carreras.

Puedes postular para asistir a OpenCon en http://www.opencon2017.org/apply.

El proceso de postulaciones se encontrará abierto hasta el 1º de agosto.
Los beneficios de postular para OpenCon 2017 se extienden más allá del
evento en Berlin: aquellos que postulen tendrán la oportunidad de ser
conectados con nuevos colaboradores, conocer sobre becas para asistir a
conferencias relacionadas, y participar activamente en una amplia
comunidad. La asistencia a OpenCon es solo a través de postulación, y son
alentados a hacerlo los estudiantes y profesionales académicos en estadios
tempranos de sus carreras de todos los niveles de experiencia.
I've already sent the previous text to someone at the Ministry of S&T in
Argentina who coordinates the National System of Repositories for her to
send it to some mailing lists. I'll send the new version hoping she hasn't
sent it  yet to try to update it.

2017-06-28 11:47 GMT-03:00 Lorraine C. <notifications@github.com>:

**Comment by char-siuu-bao** [comment]
Thanks so much @guichactis! You have been so helpful!

**Comment by JosephMcArthur** [comment]
The only thing that looks like is left on this issue is covered by #19. So, I'm closing this. Go team!
